[package]
name = "rarc"
version = "0.1.0"
authors = ["Erin Moon <erin@hashbang.sh>"]
exclude = ["data/*"]

[dependencies]
nom = "4.0"
nom-reader = "0.2"
pretty_assertions = "0.3.0"
byteorder = "1.1.0"
encoding = "0.2"
